apiVersion: v1
kind: Pod
metadata:
  name: servicio-javier-pod
  labels:
    app: servicio-javier
spec:
  containers:
    - name: servicio-javier-container
      image: servicio-javier:latest
      ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-javier-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: servicio-javier